### ISSUE TITLE
Extension not supported within a VSCode remote SSH editor

### ISSUE THREAD

**Issue by cameronmccord2** [ahmadalli/vscode-nginx-conf#17]
Required information for this issue:

- Your VS Code Version: 1.85.0
- Extension version: 0.3.2
- Your OS Version: Apple M1 Max Sonoma 14.1.2
- Is this extension running on VS Code Remote or <https://vscode.dev>: Locally works, remote on a centos linux box fails with this message
- 
```
This extension is enabled in the Local Extension Host because it prefers to run there. [Learn More](https://code.visualstudio.com/api/advanced-topics/remote-extensions)
```

Steps to Reproduce:

1. Set up a remote ssh to a linux box
2. Try to install the extension in the remote vscode window

<img width="736" alt="Screenshot 2023-12-12 at 8 36 37 PM" src="https://github.com/ahmadalli/vscode-nginx-conf/assets/2424811/4cc283bf-a20e-479a-9af6-66ca0d487ec2">

**Comment by ahmadalli** [comment]
Hello

I've tested it with Ubuntu 22.04 LTS and it's working without any issues. I'm closing this issue since CentOS 7 is EOL, and VSCode also dropped support for remote connections to CentOS 7 hosts.
